# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:5.7
    volumes:
            - ./data:/var/lib/mysql
    environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=server
    ports:
            - "3306:3306"
  