# Use root/example as user/password credentials
version: '3.1'

services:
  api:
    image: node:14-alpine
    working_dir: /code
    volumes:
            - .:/code
    ports:
            - "3000:3000"
    command: npm run watch-server
  mysql:
    image: mysql:5.7
    volumes:
            - ./data:/var/lib/mysql
    environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=server
    ports:
            - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  